const express = require('express');
const session = require('express-session');
const SQLiteStore = require('connect-sqlite3')(session);
const helmet = require('helmet');
const bcrypt = require('bcryptjs');
const QRCode = require('qrcode');
const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const path = require('path');
const crypto = require('crypto');
const { init, run, get, all, dbPath } = require('./db');
const { requireAuth, guestOnly } = require('./auth');
const app = express();
const PORT = process.env.PORT || 3000;
app.set('view engine', 'ejs'); app.set('views', path.join(__dirname, 'views'));
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.urlencoded({ extended: true })); app.use(express.json());
app.use(express.static(path.join(__dirname, '..', 'public')));
app.use(session({ store: new SQLiteStore({ db: 'sessions.sqlite', dir: path.join(__dirname, '..', 'data') }), secret: process.env.SESSION_SECRET || 'change-this-long-session-secret', resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 1000*60*60*8 } }));
app.use((req,res,next)=>{res.locals.admin=req.session.admin; res.locals.flash=req.session.flash; delete req.session.flash; next();});
const flash=(req,type,msg)=>{req.session.flash={type,msg};};
const stats = async()=>({ students: (await get('SELECT COUNT(*) c FROM students')).c, events: (await get('SELECT COUNT(*) c FROM events')).c, attendance: (await get('SELECT COUNT(*) c FROM attendance')).c, active: (await get('SELECT COUNT(*) c FROM events WHERE is_active=1')).c });
app.get('/', (req,res)=>res.redirect(req.session.admin?'/dashboard':'/login'));
app.get('/login', guestOnly, (req,res)=>res.render('login'));
app.post('/login', guestOnly, async(req,res)=>{ const a=await get('SELECT * FROM admins WHERE email=?',[req.body.email]); if(!a || !await bcrypt.compare(req.body.password||'', a.password_hash)){ flash(req,'danger','Invalid email or password.'); return res.redirect('/login'); } req.session.admin={id:a.id,name:a.name,email:a.email}; res.redirect('/dashboard'); });
app.post('/logout', requireAuth, (req,res)=>req.session.destroy(()=>res.redirect('/login')));
app.get('/dashboard', requireAuth, async(req,res)=>{ const recent=await all(`SELECT at.checked_in_at,e.title,s.name,s.student_no FROM attendance at JOIN events e ON e.id=at.event_id JOIN students s ON s.id=at.student_id ORDER BY at.checked_in_at DESC LIMIT 10`); res.render('dashboard',{stats:await stats(),recent}); });
app.get('/students', requireAuth, async(req,res)=>res.render('students',{students:await all('SELECT * FROM students ORDER BY name')}));
app.post('/students', requireAuth, async(req,res)=>{ const {student_no,name,email,department,year_level,phone}=req.body; try{await run('INSERT INTO students(student_no,name,email,department,year_level,phone) VALUES(?,?,?,?,?,?)',[student_no,name,email,department,year_level,phone]); flash(req,'success','Student added.');}catch(e){flash(req,'danger','Could not add student: '+e.message);} res.redirect('/students'); });
app.post('/students/:id/delete', requireAuth, async(req,res)=>{ await run('DELETE FROM students WHERE id=?',[req.params.id]); flash(req,'success','Student removed.'); res.redirect('/students'); });
app.get('/events', requireAuth, async(req,res)=>res.render('events',{events:await all('SELECT *,(SELECT COUNT(*) FROM attendance a WHERE a.event_id=events.id) attendees FROM events ORDER BY starts_at DESC')}));
app.post('/events', requireAuth, async(req,res)=>{ const {title,description,venue,starts_at,ends_at}=req.body; await run('INSERT INTO events(title,description,venue,starts_at,ends_at,qr_token,is_active) VALUES(?,?,?,?,?,?,1)',[title,description,venue,starts_at,ends_at,crypto.randomUUID()]); flash(req,'success','Event created.'); res.redirect('/events'); });
app.post('/events/:id/toggle', requireAuth, async(req,res)=>{ await run('UPDATE events SET is_active=CASE is_active WHEN 1 THEN 0 ELSE 1 END WHERE id=?',[req.params.id]); res.redirect('/events'); });
app.post('/events/:id/delete', requireAuth, async(req,res)=>{ await run('DELETE FROM events WHERE id=?',[req.params.id]); res.redirect('/events'); });
app.get('/events/:id/qr', requireAuth, async(req,res)=>{ const e=await get('SELECT * FROM events WHERE id=?',[req.params.id]); if(!e) return res.status(404).send('Event not found'); const scanUrl=`${req.protocol}://${req.get('host')}/scan/${e.qr_token}`; const qr=await QRCode.toDataURL(scanUrl); res.render('qr',{event:e,qr,scanUrl}); });
app.get('/scanner', requireAuth, async(req,res)=>res.render('scanner',{events:await all('SELECT * FROM events WHERE is_active=1 ORDER BY starts_at DESC')}));
app.get('/scan/:token', async(req,res)=>{ const e=await get('SELECT * FROM events WHERE qr_token=? AND is_active=1',[req.params.token]); if(!e) return res.status(404).render('public-scan',{event:null}); res.render('public-scan',{event:e}); });
app.post('/api/attendance', async(req,res)=>{ const {token,student_no}=req.body; const e=await get('SELECT * FROM events WHERE qr_token=? AND is_active=1',[token]); if(!e) return res.status(404).json({ok:false,message:'Active event not found.'}); const s=await get('SELECT * FROM students WHERE student_no=?',[student_no]); if(!s) return res.status(404).json({ok:false,message:'Student not found.'}); try{await run('INSERT INTO attendance(event_id,student_id,method) VALUES(?,?,?)',[e.id,s.id,'QR']); res.json({ok:true,message:`Welcome ${s.name}. Attendance recorded for ${e.title}.`});}catch(err){res.json({ok:true,message:`${s.name} was already checked in for ${e.title}.`});} });
app.get('/api/events/:id/live', requireAuth, async(req,res)=>{ const event=await get('SELECT * FROM events WHERE id=?',[req.params.id]); const count=(await get('SELECT COUNT(*) c FROM attendance WHERE event_id=?',[req.params.id])).c; const rows=await all(`SELECT s.student_no,s.name,s.department,a.checked_in_at FROM attendance a JOIN students s ON s.id=a.student_id WHERE a.event_id=? ORDER BY a.checked_in_at DESC LIMIT 25`,[req.params.id]); res.json({event,count,rows}); });
app.get('/attendance', requireAuth, async(req,res)=>res.render('attendance',{events:await all('SELECT * FROM events ORDER BY starts_at DESC')}));
async function reportRows(eventId){ return all(`SELECT e.title,e.venue,e.starts_at,s.student_no,s.name,s.email,s.department,s.year_level,a.checked_in_at FROM attendance a JOIN events e ON e.id=a.event_id JOIN students s ON s.id=a.student_id WHERE e.id=? ORDER BY a.checked_in_at`,[eventId]); }
app.get('/reports/:id.xlsx', requireAuth, async(req,res)=>{ const rows=await reportRows(req.params.id); const wb=new ExcelJS.Workbook(); const ws=wb.addWorksheet('Attendance'); ws.columns=['Event','Venue','Starts','Student No','Name','Email','Department','Year','Checked In'].map(h=>({header:h,key:h,width:22})); rows.forEach(r=>ws.addRow({'Event':r.title,'Venue':r.venue,'Starts':r.starts_at,'Student No':r.student_no,'Name':r.name,'Email':r.email,'Department':r.department,'Year':r.year_level,'Checked In':r.checked_in_at})); res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); res.setHeader('Content-Disposition','attachment; filename=attendance.xlsx'); await wb.xlsx.write(res); res.end(); });
app.get('/reports/:id.pdf', requireAuth, async(req,res)=>{ const rows=await reportRows(req.params.id); res.setHeader('Content-Type','application/pdf'); res.setHeader('Content-Disposition','attachment; filename=attendance.pdf'); const doc=new PDFDocument({margin:36}); doc.pipe(res); doc.fontSize(18).text('College Event Attendance Report'); doc.moveDown(); rows.forEach((r,i)=>doc.fontSize(10).text(`${i+1}. ${r.student_no} - ${r.name} - ${r.department} - ${r.checked_in_at}`)); doc.end(); });
init().then(()=>app.listen(PORT,()=>console.log(`College Event QR Attendance running on http://localhost:${PORT} using ${dbPath}`))).catch(e=>{console.error(e);process.exit(1);});
